export * from './LoginPage';
export * from './ComingSoonPage';
export * from './GenerationsPage';
export * from './GraduationOptionsPage';
export * from './CareersPage';
export * from './ModalitiesPage';
export * from './QuotasPage';
export * from './IngressEgressPage';
export * from './StudentsPage';
